title: Inward Movement
description: Writer, developer, activist
url: https://inwardmovement.github.io/
author: Victor Massé
permalink: /:categories/:title/
markdown: CommonMarkGhPages
commonmark:
options: ["SMART", "FOOTNOTES", "HARDBREAKS"]
extensions: ["strikethrough", "autolink", "table"]
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-optional-front-matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      lang: en
  -
    scope:
      path: index.md
    values:
      layout: home
  -
    scope:
      path: poems
    values:
      lang: fr
  -
    scope:
      path: poems
      type: posts
    values:
      layout: poem
  -
    scope:
      path: poems
      type: pages
    values:
      title: Poems
      layout: recueil
  -
    scope:
      path: articles
      type: posts
    values:
      layout: article
  -
    scope:
      path: blog
      type: posts
    values:
      title: Blog
      layout: blog
      permalink: /:categories/:year-:month-:day/
  -
    scope:
      path: blog
      type: pages
    values:
      title: Blog
