title: Inward Movement
description: Victor's personal website (writer, developer, activist)
url: "https://inwardmovement.github.io/"
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  hard_wrap: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      lang: en
  -
    scope:
      path: index.md
    values:
      layout: home
  -
    scope:
      path: poems
    values:
      layout: poem
      lang: fr
  -
    scope:
      path: poems
      type: pages
    values:
      layout: recueil
