title: Inward Movement
description: Victor's personal website (writer, developer, activist)
url: "https://inwardmovement.github.io/"
logo: /assets/avatar.png
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
