title: Inward Movement
description: Victor's personal website (writer, developer, activist)
url: "https://inwardmovement.github.io/"
markdown: kramdown
kramdown:
  hard_wrap: true
permalink: /:categories/:title
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
    values:
      layout: "blog"
  -
    scope:
      path: "poems"
    values:
      layout: "poem"
  -
    scope:
      path: "poems"
      type: "pages"
    values:
      layout: "recueil"
