title: Inward Movement
description: Victor's personal website (writer, developer, activist)
url: "https://inwardmovement.github.io/"
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
